# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_bin_quantile_rec <- function(rn, rp, rnmin, rnmax, rminprob, rdir) {
    .Call('motifDiverge_rcpp_bin_quantile_rec', PACKAGE = 'motifDiverge', rn, rp, rnmin, rnmax, rminprob, rdir)
}

rcpp_convolve <- function(rx, ry) {
    .Call('motifDiverge_rcpp_convolve', PACKAGE = 'motifDiverge', rx, ry)
}

rcpp_prob_sym <- function(rk, rn, rp10, rp01, rerr) {
    .Call('motifDiverge_rcpp_prob_sym', PACKAGE = 'motifDiverge', rk, rn, rp10, rp01, rerr)
}

